list(
  APPEND
  PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/chart_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/component_with_previews/component_with_previews_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/extends_widget_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/h3_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/my_animated_button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/my_animated_list_item_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/mybutton_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/super_button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_sm_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/Nunito_SemiBold_ttf_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_bell_data.c
  ${CMAKE_CURRENT_LIST_DIR}/reference_project_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/reference_project.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/a_permanent_screen_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/animations_screen_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/main_screen_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_extends_something_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/some_screen_1_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/test_widgets_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/extends_another/extends_another_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/extends_another/extends_another_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/extends_another/extends_another.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/myarc/myarc_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/myarc/myarc_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/myarc/myarc.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/set_element/set_element_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/set_element/set_element_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/set_element/set_element.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/smart_slider/smart_slider_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/smart_slider/smart_slider_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/smart_slider/smart_slider.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/super_nested_components/super_nested_components_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/super_nested_components/super_nested_components_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/super_nested_components/super_nested_components.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/super_nested/super_nested_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/super_nested/super_nested_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/super_nested/super_nested.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/very_simple/very_simple_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/very_simple/very_simple_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/very_simple/very_simple.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/with_getter/with_getter_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/with_getter/with_getter_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/with_getter/with_getter.c)