set(LV_EDITOR_PROJECT_SOURCES)
list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/chart/chart_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/ui_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/ui.c)